#
# Category Management.
#
ccdn_forum_admin_category_index:
    pattern: /{_locale}/admin/forum/category/index
    defaults: { _controller: CCDNForumAdminBundle:Category:index, _locale: en }

ccdn_forum_admin_category_create:
    pattern: /{_locale}/admin/forum/category/create
    defaults: { _controller: CCDNForumAdminBundle:Category:create, _locale: en }

ccdn_forum_admin_category_edit:
    pattern: /{_locale}/admin/forum/category/{categoryId}/edit
    defaults: { _controller: CCDNForumAdminBundle:Category:edit, _locale: en }

ccdn_forum_admin_category_delete:
    pattern: /{_locale}/admin/forum/category/{categoryId}/delete
    defaults: { _controller: CCDNForumAdminBundle:Category:delete, _locale: en }

ccdn_forum_admin_category_delete_confirmed:
    pattern: /{_locale}/admin/forum/category/{categoryId}/confirmed/delete
    defaults: { _controller: CCDNForumAdminBundle:Category:deleteConfirmed, _locale: en }

ccdn_forum_admin_category_priority_move_up:
    pattern: /{_locale}/admin/forum/category/{categoryId}/reorder/up
    defaults: { _controller: CCDNForumAdminBundle:Category:reorder, _locale: en, direction: 'up' }

ccdn_forum_admin_category_priority_move_down:
    pattern: /{_locale}/admin/forum/category/{categoryId}/reorder/down
    defaults: { _controller: CCDNForumAdminBundle:Category:reorder, _locale: en, direction: 'down' }

#
# Board Management.
#
ccdn_forum_admin_board_create:
    pattern: /{_locale}/admin/forum/board/create
    defaults: { _controller: CCDNForumAdminBundle:Board:create, _locale: en, categoryId: 1 }

ccdn_forum_admin_board_create_on_category:
    pattern: /{_locale}/admin/forum/board/create/on/category/{categoryId}
    defaults: { _controller: CCDNForumAdminBundle:Board:create, _locale: en }

ccdn_forum_admin_board_edit:
    pattern: /{_locale}/admin/forum/board/{boardId}/edit
    defaults: { _controller: CCDNForumAdminBundle:Board:edit, _locale: en }

ccdn_forum_admin_board_delete:
    pattern: /{_locale}/admin/forum/board/{boardId}/delete
    defaults: { _controller: CCDNForumAdminBundle:Board:delete, _locale: en }

ccdn_forum_admin_board_delete_confirmed:
    pattern: /{_locale}/admin/forum/board/{boardId}/delete/confirmed
    defaults: { _controller: CCDNForumAdminBundle:Board:deleteConfirmed, _locale: en }

ccdn_forum_admin_board_priority_move_up:
    pattern: /{_locale}/admin/forum/board/{boardId}/reorder/up
    defaults: { _controller: CCDNForumAdminBundle:Board:reorder, _locale: en, direction: 'up' }

ccdn_forum_admin_board_priority_move_down:
    pattern: /{_locale}/admin/forum/board/{boardId}/reorder/down
    defaults: { _controller: CCDNForumAdminBundle:Board:reorder, _locale: en, direction: 'down' }


#
# Topic Management.
#
ccdn_forum_admin_topic_deleted_show_all:
    pattern: /{_locale}/admin/forum/topics/deleted/show
    defaults: { _controller: CCDNForumAdminBundle:Topic:showDeleted, _locale: en }

ccdn_forum_admin_topic_deleted_bulk_action:
    pattern: /{_locale}/admin/forum/topics/deleted/bulk/action
    defaults: { _controller: CCDNForumAdminBundle:Topic:deletedBulk, _locale: en }

ccdn_forum_admin_topic_closed_show_all:
    pattern: /{_locale}/admin/forum/topic/show/closed
    defaults: { _controller: CCDNForumAdminBundle:Topic:showClosed, _locale: en }

ccdn_forum_admin_topic_closed_bulk_action:
    pattern: /{_locale}/admin/forum/topic/closed/action/checked
    defaults: { _controller: CCDNForumAdminBundle:Topic:closedBulk, _locale: en }

#
# Post Management.
#
ccdn_forum_admin_post_deleted_show_all:
    pattern: /{_locale}/admin/forum/posts/deleted/show
    defaults: { _controller: CCDNForumAdminBundle:Post:showDeleted, _locale: en }

ccdn_forum_admin_post_deleted_bulk_action:
    pattern: /{_locale}/admin/forum/posts/deleted/bulk/action
    defaults: { _controller: CCDNForumAdminBundle:Post:deletedBulk, _locale: en }

ccdn_forum_admin_post_locked_show_all:
    pattern: /{_locale}/admin/forum/post/show/locked
    defaults: { _controller: CCDNForumAdminBundle:Post:showLocked, _locale: en }

ccdn_forum_admin_post_locked_bulk_action:
    pattern: /{_locale}/admin/forum/post/locked/action/checked
    defaults: { _controller: CCDNForumAdminBundle:Post:lockedBulk, _locale: en }
