parameters:

    ccdn_forum_admin.category.manager.class:                    CCDNForum\AdminBundle\Manager\CategoryManager
    ccdn_forum_admin.board.manager.class:                       CCDNForum\AdminBundle\Manager\BoardManager
    ccdn_forum_admin.topic.manager.class:                       CCDNForum\AdminBundle\Manager\TopicManager
    ccdn_forum_admin.post.manager.class:                        CCDNForum\AdminBundle\Manager\PostManager

    ccdn_forum_admin.category.form.type.class:                  CCDNForum\AdminBundle\Form\Type\CategoryType
    ccdn_forum_admin.category.form.insert.handler.class:        CCDNForum\AdminBundle\Form\Handler\CategoryInsertFormHandler
    ccdn_forum_admin.category.form.update.handler.class:        CCDNForum\AdminBundle\Form\Handler\CategoryUpdateFormHandler

    ccdn_forum_admin.board.form.type.class:                     CCDNForum\AdminBundle\Form\Type\BoardType
    ccdn_forum_admin.board.form.insert.handler.class:           CCDNForum\AdminBundle\Form\Handler\BoardInsertFormHandler
    ccdn_forum_admin.board.form.update.handler.class:           CCDNForum\AdminBundle\Form\Handler\BoardUpdateFormHandler

    ccdn_forum_admin.topic.manager.class:                       CCDNForum\AdminBundle\Manager\TopicManager
    ccdn_forum_admin.post.manager.class:                        CCDNForum\AdminBundle\Manager\PostManager

    ccdn_forum_admin.topic.form.change_board.type.class:        CCDNForum\AdminBundle\Form\Type\TopicChangeBoardType
    ccdn_forum_admin.topic.form.change_board.handler.class:     CCDNForum\AdminBundle\Form\Handler\TopicChangeBoardFormHandler

    ccdn_forum_admin.dashboard.integrator.class:                CCDNForum\AdminBundle\Component\Dashboard\DashboardIntegrator

services:

    #
    # Managers.
    #
    ccdn_forum_admin.category.manager:
        class:  %ccdn_forum_admin.category.manager.class%
        arguments:  [@doctrine, @service_container]
    ccdn_forum_admin.board.manager:
        class:  %ccdn_forum_admin.board.manager.class%
        arguments:  [@doctrine, @service_container]
    ccdn_forum_admin.topic.manager:
        class: %ccdn_forum_admin.topic.manager.class%
        arguments:  [@doctrine, @service_container]
    ccdn_forum_admin.post.manager:
        class: %ccdn_forum_admin.post.manager.class%
        arguments:  [@doctrine, @service_container]
        
    #
    # Category Forms.
    #
    ccdn_forum_admin.category.form.type:
        class:  %ccdn_forum_admin.category.form.type.class%
        arguments:  [@doctrine]
    ccdn_forum_admin.category.form.insert.handler:
        class:  %ccdn_forum_admin.category.form.insert.handler.class%
        arguments:  [@form.factory, @service_container, @ccdn_forum_admin.category.manager]
    ccdn_forum_admin.category.form.update.handler:
        class:  %ccdn_forum_admin.category.form.update.handler.class%
        arguments:  [@form.factory, @service_container, @ccdn_forum_admin.category.manager]

    #
    # Board Forms.
    #
    ccdn_forum_admin.board.form.type:
        class:  %ccdn_forum_admin.board.form.type.class%
        arguments:  [@doctrine]
    ccdn_forum_admin.board.form.insert.handler:
        class:  %ccdn_forum_admin.board.form.insert.handler.class%
        arguments:  [@form.factory, @service_container, @ccdn_forum_admin.board.manager]
    ccdn_forum_admin.board.form.update.handler:
        class:  %ccdn_forum_admin.board.form.update.handler.class%
        arguments:  [@form.factory, @service_container, @ccdn_forum_admin.board.manager]

    #
    # Topic Forms.
    #
    ccdn_forum_admin.topic.form.change_board.type:
        class:  %ccdn_forum_admin.topic.form.change_board.type.class%
        arguments:  [@doctrine]
    ccdn_forum_admin.topic.form.change_board.handler:
        class:  %ccdn_forum_admin.topic.form.change_board.handler.class%
        arguments:  [@form.factory, @service_container, @ccdn_forum_admin.topic.manager]
        
    #
    # Dashboard Integrator.
    #
    ccdn_forum_admin.dashboard.integrator:
        class: %ccdn_forum_admin.dashboard.integrator.class%
        arguments: [@service_container]
        tags:
            - { name: ccdn_component_dashboard.integrator }
