%ccdn_forum_admin.entity.category.class%:
    properties:
        name:
            - Type: { type: string, groups: [admin_category_create, admin_category_update] }
            - NotBlank: { groups: [admin_category_create, admin_category_update] }
            - MinLength: { limit: 2, groups: [admin_category_create, admin_category_update] }
            - MaxLength: { limit: 255, groups: [admin_category_create, admin_category_update] }

%ccdn_forum_admin.entity.board.class%:
    properties:
        name:
            - Type: { type: string, groups: [admin_board_create, admin_board_update] }
            - NotBlank: { groups: [admin_board_create, admin_board_update] }
            - MinLength: { limit: 2, groups: [admin_board_create, admin_board_update] }
            - MaxLength: { limit: 255, groups: [admin_board_create, admin_board_update] }
        description:
            - Type: { type: string, groups: [admin_board_create, admin_board_update] }
            - NotBlank: { groups: [admin_board_create, admin_board_update] }
            - MinLength: { limit: 5, groups: [admin_board_create, admin_board_update] }
            - MaxLength: { limit: 1000, groups: [admin_board_create, admin_board_update] }
